#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use Data::Dump 'pp';
use Teach::Tutor; # Don't forget to call: submit(<variable>);

my $str = join(':', @ARGV);

submit($str);
say pp($str);