#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

my $str = $ARGV[0];
my $str_upper = uc($str);
my $filename = $ARGV[1];

open (my $fh, '<', $filename);
while (my $line = <$fh>) {
    print $line if $line =~ s/$str/$str_upper/g;
}
close $fh;