#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

my $str = $ARGV[0];
my $str_upper = uc($str);
my $filename = $ARGV[1];

open (my $fh, '<', $filename);
while (my $line = <$fh>) {
    my @parts = split /\s/, $line;
    my @new_list = map {  $_ =~ qr/$str/ ? uc($_) : $_ } @parts; 
    my $new_str = join(' ', @new_list);
    say $new_str;
}
close $fh;