#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

my $str_1 = $ARGV[0];
my $str_2 = $ARGV[1];
my $filename = $ARGV[2];

open(my $fh, '<', $filename);

while (my $line = <$fh>) {
    $line =~ s/($str_1.*?$str_2)/\U$1\E/;
    print $line;
}

close $fh