#!/usr/bin/perl

use strict;
use warnings;

my @data = (
  { value => undef, representation => q(undef) },
  { value => 0, representation => q(0) },
  { value => '0', representation => q('0') },
  { value => '',  representation => q('') },
  { value  => 0.000, representation => q(0.000) },
  { value  => '0.000'  , representation => q('0.000') },
  { value  => "0.000" , representation => q("0.000") },
  { value  => " " , representation => q(" ") },
);

foreach my $dat (@data) {
  print "The code [".$dat->{representation}."] evaluates as ";
  if ($dat->{value}) {
    print "zero\n";
  }
  else {
    print "not zero\n";
  }
}

my $var;
print 'When unassigned $var is ';
if ($var == 0) {
  print "zero\n";
}
else {
  print "not zero\n";
}


