#!/usr/bin/perl

use strict;
use warnings;
use Data::Dump 'pp';
use feature 'say';

sub get_max_value_key {
  my %hash_args = @_;
  my $curr_max = 0;
  my $curr_key;
  
  # TODO: Implement me!
  foreach my $key (keys %hash_args)
    {
    my $value = $hash_args{$key};
        if ($value >= $curr_max)
        {
            $curr_max = $value;
            $curr_key = $key;
        }
    }
    return $curr_key;
  
}

my %exam_marks = (anna => 85, bob => 96, chloe => 78, dave => 64);

say 'Highest mark awarded to '.get_max_value_key(%exam_marks);

